### ISSUE TITLE
readme outdated

### ISSUE THREAD

**Issue by nao3301** [puzzlepeaches/Log4jUnifi#1]
Hi Guys, 

docker has apparently changed something so that the command under [install with docker](https://github.com/puzzlepeaches/Log4jUnifi#docker-install) not longer works:

`docker build -t Log4jUnifi .`

It throws this error:
```
invalid argument "Log4jUnifi" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
See 'docker build --help'.
```

the fixed command would look like this:

`docker build -t log4junify:1.0 .`

Thanks for the nice work, keep it up :)
Cheers

**Comment by puzzlepeaches** [comment]
Changed the README. Thanks for calling this out!
